### PR TITLE
Support for a non root installation

### PR DESCRIPTION
**Pull request by marcoskubis**
If the installation is on a subfolder of your server, you can set:

` window.Laravel.rootFolder = 'folder'`

### CODE REVIEW

**Comment by guiwoda** [comment]
@marcoskubis would you mind explaining your intent with this?

**Comment by marcoskubis** [comment]
@guiwoda If the installation is on a subfolder of your server, the `Router.route()` return a wrong url. 

Example:

    Base url: www.example.com/myapp
    Router.route('dashboard') // returns http://example.com/
    Router.route('settings') // returns http://example.com/settings instead of http://example.com/myapp/settings


This pull request allows configure a root folder for your package.

**Comment by guiwoda** [comment]
Hey @marcoskubis 
I'm deprecating this package in favor of https://github.com/aaronlord/laroute

Please check if they support your use cases, and sorry for the inconvenience!

**Comment by marcoskubis** [comment]
Thanks @guiwoda, I'll check out that.

**Pull request closed without merging**
